### ISSUE TITLE
TraCeR integration with R-based tools 

### ISSUE THREAD

**Issue by andresnoe** [Teichlab/tracer#106]
Hi Mike,

Thanks for your work on TraCeR. I've just run it on my SmartSeq2 data set and am wondering if there are any straightforward methods for integration with R-based tools/workflows? I'm thinking something similar to scRepertoire's ability to take filtered contig outputs from 10x Cell Ranger (or similarly, ImmunArch (used to be called tcR)). I've been looking for a few days now and can't find anything that seems to pull in the TraCeR output simply. Ideally, I'd want something that allows me to do clonotype-only analysis functions (eg. unique clonotypes) and look at interaction with mRNA expression data using Seurat or SingleCellExperiment objects. Open to broad brush stroke ideas.

Warm regards,

Andrés

**Comment by andresnoe** [comment]
Ah... forgot to mention the main inspiration for this post. I saw [this pre-print](https://www.biorxiv.org/content/10.1101/2020.04.10.035865v1.full.pdf) for scirpy, single-cell T-cell receptor sequencing data analysis tool. Is there any similar R equivalent?

**Comment by mstubb** [comment]
Hi Andrés, 

Unfortunately, I don't know of any R-based tools that parse TraCeR output. Sorry. 

If you were willing to work in Python then I think scirpy could help with what you want but I don't have any direct experience with it.

Very best,

Mike
