### ISSUE TITLE
Got an error in Running Kallisto

### ISSUE THREAD

**Issue by zhouxinseeu** [Teichlab/tracer#107]
##Making Kallisto indices##
  File "/SGRNJ/Public/Software/tracer/tracer", line 21, in <module>
    launch()
  File "/SGRNJ01/Public/Software/tracer/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/SGRNJ01/Public/Software/tracer/tracerlib/tasks.py", line 373, in run
    self.quantify(cell)
  File "/SGRNJ01/Public/Software/tracer/tracerlib/tasks.py", line 627, in quantify
    self.fragment_length, self.fragment_sd)
  File "/SGRNJ01/Public/Software/tracer/tracerlib/tracer_func.py", line 1352, in quantify_with_kallisto
    subprocess.check_call(index_command)
  File "/SGRNJ/Public/Software/conda_env/vdjpuzzle1/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/SGRNJ/Public/Software/conda_env/vdjpuzzle1/bin/kallisto', 'index', '-i', '/SGRNJ01/RD_dir/pipeline_test/zhouyiqi/users/zhouxin/test/cell1/expression_quantification/kallisto_index/cell1_transcriptome.idx', '/SGRNJ01/RD_dir/pipeline_test/zhouyiqi/users/zhouxin/test/cell1/expression_quantification/kallisto_index/cell1_transcriptome.fa']' returned non-zero exit status -9

and my command is 
/SGRNJ/Public/Software/tracer/tracer assemble \
 --fragment_length 150\
 --fragment_sd 5\
 --single_end\
 --species Hsap\
 -c /SGRNJ01/RD_dir/pipeline_test/zhouyiqi/unittest/tcr_fl/20201103/tracer_SGR.conf \
 /SGRNJ01/RD_dir/pipeline_test/zhouyiqi/unittest/tcr_fl/pipe/GOT0928_P1_T/03.split_fq/fastq/1.fq cell1 ./

I don't know why cuz this shell can work normally before, but it failed this time. I need your help if it is convenient. Thank you!

**Comment by mstubb** [comment]
What happens if you run the following command at the command line?

`/SGRNJ/Public/Software/conda_env/vdjpuzzle1/bin/kallisto index -i /SGRNJ01/RD_dir/pipeline_test/zhouyiqi/users/zhouxin/test/cell1/expression_quantification/kallisto_index/cell1_transcriptome.idx /SGRNJ01/RD_dir/pipeline_test/zhouyiqi/users/zhouxin/test/cell1/expression_quantification/kallisto_index/cell1_transcriptome.fa`

**Comment by zhouxinseeu** [comment]
Thank you for your reply. I have solved the problem. It took a long time while running kallisto index, so the server killed my program. Maybe a faster software is needed.
