### ISSUE TITLE
Running tracer on 10x Genomics data

### ISSUE THREAD

**Issue by abiswas97** [Teichlab/tracer#111]
I'm trying to use tracer on some 10x genomics fastq files, and noticed I'd have to demultiplex them to be used. 

I found this thread (https://github.com/Teichlab/tracer/issues/58) from a couple years ago that mentioned tracer hadn't been validated for 10x data. Have their been any updates on this? Will demultiplexing using something like Sabre provide reliable output, or is this not recommended?

**Comment by mstubb** [comment]
Hi,

No, TraCeR still isn't recommended/intended for use with 10x data. You could try Sabre but I haven't got any experience with it. 

Very best,

Mike
