### ISSUE TITLE
tracer crashes after IgBLAST

### ISSUE THREAD

**Issue by prefectus** [Teichlab/tracer#15]
First of all thank you very much for this extremely useful tool. 
We get an error after the Running IgBLAST part. Independent whether I try the test_data (mouse) or our own data (human): 

##Running IgBLAST##
##TCRA##
##TCRB##

Traceback (most recent call last):
  File "/Seq/tools/tracer/tracer", line 21, in <module>
    Launcher().launch()
  File "/Seq/tools/tracer/tracerlib/launcher.py", line 54, in launch
    getattr(self, args.mode)()
  File "/Seq/tools/tracer/tracerlib/launcher.py", line 217, in assemble
    cell = io.parse_IgBLAST(locus_names, output_dir, cell_name, imgt_seq_location, species, seq_method)
  File "/Seq/tools/tracer/tracerlib/io.py", line 76, in parse_IgBLAST
    cell = find_possible_alignments(all_locus_data, locus_names, cell_name, IMGT_seqs, output_dir, species, seq_method)
  File "/Seq/tools/tracer/tracerlib/tracer_func.py", line 103, in find_possible_alignments
    processed_hit_table = process_hit_table(query_name, query_data, locus)
  File "/Seq/tools/tracer/tracerlib/tracer_func.py", line 237, in process_hit_table
    segment = entry[2]
IndexError: list index out of range

Do you have any idea what could be wrong?
Reagrds,
Till

**Comment by mstubb** [comment]
Hi,

Are you using a version of Igblast newer than 1.4.0. That error message looks like the output format may have changed in the versions that were released this year and so the parser is failing to extract the correct information. If you are using a newer version, the best fix for now will be to download v1.4.0 (ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release//1.4.0) and to see if that works. We’re currently preparing a relatively large update for release and we’ll add support for newer IgBLAST versions in that. In the meantime, if this is the cause, I’ll update the README to emphasise the need to use v1.4.0.

Please let me know if changing IgBLAST version fixes the problem. If it does not, we can investigate further to find out what’s going on.

Best,

Mike

**Comment by prefectus** [comment]
Dear Mike,
you were right. I used IgBLAST 1.6.0. After downgrading to 1.4.0 it worked like a charm.

Thank you very much,
Till

**Comment by mstubb** [comment]
Oh great. Glad it's working, thanks for letting me know!

I'll work on adding compatibility for later versions of IgBLAST in the next release. 

Best,

Mike
