### ISSUE TITLE
Add support for IgBLAST versions above v1.4.0

### ISSUE THREAD

**Issue by mstubb** [Teichlab/tracer#16]
It seems that the output format from IgBLAST changed between v1.4.0 and later versions. This means that `process_hit_table` doesn't parse the results properly. This needs fixing.

**Comment by mikessh** [comment]
Hello! Sorry for off-topic, as a person who heavily relies on IgBlast I've just discovered v1.6.0 from Tracer issue tracker. Are you aware what are the changes/improvements in v1.6.0 (the changelog from NCBI ftp is just a copy-paste of v1.4.0 one)?

**Comment by mstubb** [comment]
Hi @mikessh! Sadly, I don't know what the changes are. They've obviously changed something about the formatting of the output that Tracer uses but I haven't yet had time to investigate anything else in detail. 

There was supposed to be a poster at the recent AAI meeting in Seattle titled ["An update on IgBLAST, a tool for Ig and TCR sequence analysis"](http://www.jimmunol.org/content/196/1_Supplement/138.3.abstract) but, annoyingly, it wasn't actually on display.

I'll let you know if I find anything out during testing.

Best,

Mike

**Comment by mstubb** [comment]
It looks like an extra line has been added almost at the end of the IgBLAST output. In version 1.4.0, the end of the file looks like:
```
# Hit table (the first field indicates the chain type of the hit)
# Fields: query id, subject id, % identity, alignment length, mismatches, gap opens, gaps, q. start, q. end, s. start, s. end, evalue, bit score
# 10 hits found
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3-3*01	100.00	280	0	0	0	14	293	1	280	9e-125	  438
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3D-3*01	99.64	280	1	0	0	14	293	1	280	8e-124	  434
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3N-3*01	98.57	280	4	0	0	14	293	1	280	5e-121	  425
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3D-3*02	98.57	280	4	0	0	14	293	1	280	5e-121	  425
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3-1*01	89.64	280	29	0	0	14	293	1	280	2e-97	  347
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ26*01	100.00	55	0	0	0	298	352	6	60	4e-27	  109
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ42*01	100.00	10	0	0	0	314	323	26	35	2.7	20.3
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ27*01	100.00	9	0	0	0	312	320	19	27	   11	18.3
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ21*01	100.00	8	0	0	0	327	334	32	39	   43	16.4
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ9*02	100.00	8	0	0	0	316	323	22	29	   43	16.4
# BLAST processed 2 queries

```
Now, it looks like:

```
# Hit table (the first field indicates the chain type of the hit)
# Fields: query id, subject id, % identity, alignment length, mismatches, gap opens, gaps, q. start, q. end, s. start, s. end, evalue, bit score
# 10 hits found
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3-3*01	100.000	280	0	0	0	14	293	1	280	9.50e-125	438
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3D-3*01	99.643	280	1	0	0	14	293	1	280	8.23e-124	434
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3N-3*01	98.571	280	4	0	0	14	293	1	280	5.37e-121	425
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3D-3*02	98.571	280	4	0	0	14	293	1	280	5.37e-121	425
V	reversed|TRINITY_DN0_c0_g2_i1	TRAV3-1*01	89.643	280	29	0	0	14	293	1	280	1.52e-97	347
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ26*01	100.000	55	0	0	0	298	352	6	60	3.82e-27	109
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ42*01	100.000	10	0	0	0	314	323	26	35	2.7	20.3
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ27*01	100.000	9	0	0	0	312	320	19	27	11	18.3
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ21*01	100.000	8	0	0	0	327	334	32	39	43	16.4
J	reversed|TRINITY_DN0_c0_g2_i1	TRAJ9*02	100.000	8	0	0	0	316	323	22	29	43	16.4

Total queries = 2, queries with identifiable CDR3 = 0

# BLAST processed 2 queries
```

The additional blank lines and lack of `#` at the start of the `Total queries` line were messing up the output parser. 

This is now fixed in both the master branch and in the branch for the big update that's coming soon (implementing_build).
