### ISSUE TITLE
Issue running on windows

### ISSUE THREAD

**Issue by baracus37** [Teichlab/tracer#20]
Hello,

I am trying to use Tracer on a Windows 7 machine within cygwin. I followed the instructions posted here and when trying to test the installtion I get the following error message:

> Traceback (most recent call last):
  File "tracer", line 21, in <module>
    Launcher().launch()
  File "E:\tools\tracer\tracerlib\launcher.py", line 54, in launch
    getattr(self, args.mode)()
  File "E:\tools\tracer\tracerlib\launcher.py", line 878, in test
    single_end=False, fragment_length=False, fragment_sd=False)
  File "E:\tools\tracer\tracerlib\launcher.py", line 160, in assemble
    subprocess.check_output([trinity, '--version'])
  File "C:\Anaconda2\lib\subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Anaconda2\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Anaconda2\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden

The last line translates to "WindowsError: [Error 2] The system cannot find the file specified"
I checked manually and all indicated files are where they are supposed to be.
I am using Python 2.7.12 :: Anaconda 4.1.1 (64-bit)

Can anyone help?

**Comment by mstubb** [comment]
Hi,

I think that I might know what the problem is here. Please could you send me your configuration file.

Thanks a lot,

Mike

**Comment by baracus37** [comment]
Hi,

thanks for your quick reply. Here you go:
(I had to add *.txt as for some reason I was unable to upload zip-files...)

[tracer.conf.txt](https://github.com/Teichlab/tracer/files/500272/tracer.conf.txt)

**Comment by mstubb** [comment]
Can you try the code on branch `iss20` (https://github.com/Teichlab/tracer/tree/iss20) and let me know if it fixes the problem?

I can't test on windows so I'm very grateful for your input. Please let me know if you encounter any other issues.

Best,

Mike

**Comment by baracus37** [comment]
I tried your new code, but unfortunately I still get the same error.

**Comment by mstubb** [comment]
Ah, I’ve worked this out. When you specify paths in your config file, you need to include the executable file. For example, the Trinity line should be:

trinity_path = /trinityrnaseq_r20140717/Trinity

Please can you change your config file to do this for all the executables and then try again.

Thanks,

Mike

**Comment by baracus37** [comment]
Thanks for all your effort, but sadly I still get the same error after including the executable files.

**Comment by mstubb** [comment]
Ok, thanks for letting me know.

Can you execute 

/trinityrnaseq_r20140717/Trinity 

from a cygwin command line?

If so, I’ll have a think and we can do some more troubleshooting. 

M

**Comment by baracus37** [comment]
Trinity doesnt seem to be working as well. I am now trying with Ubuntu in VirtualBox or as standalone.

**Comment by baracus37** [comment]
I am now using Ubuntu in VirtualBox an I was able to make some progress ;)
Trinity seems to run fine when running "tracer test", but IgBLAST returns a similiar error:

> ##Running IgBLAST##
##TCRA##
Traceback (most recent call last):
  File "tracer", line 21, in <module>
    Launcher().launch()
  File "/home/tobias/tracer/tracerlib/launcher.py", line 54, in launch
    getattr(self, args.mode)()
  File "/home/tobias/tracer/tracerlib/launcher.py", line 878, in test
    single_end=False, fragment_length=False, fragment_sd=False)
  File "/home/tobias/tracer/tracerlib/launcher.py", line 212, in assemble
    should_resume)
  File "/home/tobias/tracer/tracerlib/launcher.py", line 490, in run_IgBlast
    subprocess.check_call(command, stdout=out, stderr=DEVNULL)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['//home/tobias/tracer/ncbi-igblast-1.5.0/bin/igblastn', '-germline_db_V', '//home/tobias/tracer/resources/igblast_dbs/mouse/imgt_tcr_db_v.fa', '-germline_db_D', '//home/tobias/tracer/resources/igblast_dbs/mouse/imgt_tcr_db_d.fa', '-germline_db_J', '//home/tobias/tracer/resources/igblast_dbs/mouse/imgt_tcr_db_j.fa', '-domain_system', 'imgt', '-organism', 'mouse', '-ig_seqtype', 'TCR', '-show_translation', '-num_alignments_V', '5', '-num_alignments_D', '5', '-num_alignments_J', '5', '-outfmt', '7', '-query', '/home/tobias/tracer/test_data/results/cell1/Trinity_output/cell1_TCRA.Trinity.fasta']' returned non-zero exit status 1

**Comment by mstubb** [comment]
What happens if you run the following at the command line?

//home/tobias/tracer/ncbi-igblast-1.5.0/bin/igblastn -germline_db_V //home/tobias/tracer/resources/igblast_dbs/mouse/imgt_tcr_db_v.fa -germline_db_D //home/tobias/tracer/resources/igblast_dbs/mouse/imgt_tcr_db_d.fa -germline_db_J //home/tobias/tracer/resources/igblast_dbs/mouse/imgt_tcr_db_j.fa -domain_system imgt -organism mouse -ig_seqtype TCR -show_translation -num_alignments_V 5 -num_alignments_D 5 -num_alignments_J 5 -outfmt 7 -query /home/tobias/tracer/test_data/results/cell1/Trinity_output/cell1_TCRA.Trinity.fasta

IgBLAST is a bit tricky to get working so if this doesn’t run either please check the following two things:

1. Check that you’ve downloaded the internal_data directory from ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/internal_data <ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/internal_data> and put it in the same directory as your igblast executable (//home/tobias/tracer/ncbi-igblast-1.5.0/bin).

2. Check that you have set the $IGDATA environment variable to be the directory that contains the igblast executable. Run the following command (and put it in your .bashrc or .profile so that it’s set in every session):

export IGDATA=//home/tobias/tracer/ncbi-igblast-1.5.0/bin/

Let me know if either of those help.

Best,

Mike

**Comment by baracus37** [comment]
Hello Mike,

adding "export IGDATA=//home/tobias/tracer/ncbi-igblast-1.5.0/bin/" to the .bashrc did the trick. Thanks a lot. The tracer test now ran fine.
 
Just one last question: As tracer is run on individual cells, what would be the best way to run automatically on several  hundred or thousands of cells?

Best,

Tobias

**Comment by mstubb** [comment]
Glad it works!

When I run it on large numbers of cells I tend to write a python script to automate submitting multiple jobs to our cluster (one for each cell). You could also do it with a bash script or other similar methods. 

If you don't have access to a cluster I think that the best plan is a script that processes each cell one after another. 

Best,

Mike

**Comment by baracus37** [comment]
Hi Mike,

we are running Tracer locally. Would you mind sharing such an example script, with some instructions for use? Unfortunately I do not have any experience in writing scripts.

Best, 

Tobias
