### ISSUE TITLE
tracer crashes after Kallisto

### ISSUE THREAD

**Issue by zji90** [Teichlab/tracer#21]
Hi,
I am running tracer on the example cell1_1.fastq and cell1_2.fastq that come with the software package. All the previous steps are successfully performed including Kallisto. Then tracer throws an error that says:
Traceback (most recent call last):
  File "tracer", line 21, in <module>
    Launcher().launch()
  File "/scratch/users/zji4@jhu.edu/tracer/tracer/tracerlib/launcher.py", line 54, in launch
    getattr(self, args.mode)()
  File "/scratch/users/zji4@jhu.edu/tracer/tracer/tracerlib/launcher.py", line 232, in assemble
    tpm = counts[locus][rec.contig_name]
KeyError: 'TR1|c0_g2_i1'

I checked the "abundance.tsv" file under "expression_quantification" folder in the output folder and the last four lines are:
TCR|TR1|c0_g1_i1|TRBV12-1_GCTCTACAACAGGGGGGGCACCG_TRBJ2-2   600 494.667 63.0889 48589
TCR|TR1|c0_g2_i1|TRBV4_AGCTACAACTCCT_TRBJ2-7    592 486.667 371.938 291163
TCR|TR1|c0_g1_i1|TRAV9D-4_GTGAGGGGGAAGGAGAGGCA_TRAJ37   760 654.667 165.336 96215.7
TCR|TR1|c0_g2_i1|TRAV4-2_TTGAGAATAA_TRAJ43  738 632.667 350.764 211221

I was running tracer on CentOS system. I am wondering whether this is actually an error and how I can fix it. Thanks!

**Comment by mstubb** [comment]
Please can you send me the command you ran along with your configuration file. 

Please also zip and send me the IgBLAST_output and Trinity_output subdirectories from the cell1 output directory. 

Thanks,

Mike

**Comment by zji90** [comment]
Hi Mike,
Please see attached for the zipped file.
run.sh: the command I used to run tracer
tracer.conf: the tracer configuration file
IgBLAST_output: the output of IgBLAST
Trinity_output: the output of Trinity

Thank you very much for your help!




Best,
Jason

--
Zhicheng Ji
PhD Student
Department of Biostatistics
Bloomberg School of Public Health
Johns Hopkins University

**Comment by yotamd** [comment]
Hi Mike

I am having a similar issue using tracer 0.5.1. During the test run ('tracer test -c tracer.conf') I get the following error:

##Quantifying with Kallisto##

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 88,202
[index] number of k-mers: 82,099,927
[index] number of equivalence classes: 297,324
[quant] running in paired-end mode
[quant] will process pair 1: /seq/epiprod02/old-epigenome01/Shared/software/tracer-0.5.1/test_data/cell1_1.fastq
                             /seq/epiprod02/old-epigenome01/Shared/software/tracer-0.5.1/test_data/cell1_2.fastq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 1,135 reads, 1,052

 reads pseudoaligned
[quant] estimated average fragment length: 106.333
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 36 rounds


Traceback (most recent call last):
  File "./tracer", line 21, in <module>
    launch()
  File "/seq/epiprod02/old-epigenome01/Shared/software/tracer-0.5.1/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/seq/epiprod02/old-epigenome01/Shared/software/tracer-0.5.1/tracerlib/tasks.py", line 1079, in run
    loci=['A', 'B'], max_junc_len=50).run()
  File "/seq/epiprod02/old-epigenome01/Shared/software/tracer-0.5.1/tracerlib/tasks.py", line 324, in run
    self.quantify(cell)
  File "/seq/epiprod02/old-epigenome01/Shared/software/tracer-0.5.1/tracerlib/tasks.py", line 530, in quantify
    tpm = counts[receptor][locus][rec.contig_name]
KeyError: 'TR1|c0_g1_i1'


----

Is there any workaround?

Thank you,
Yotam

**Comment by mstubb** [comment]
Hi Yotam,

What version of Trinity are you using? I'm pretty sure that this is due to early versions of Trinity v2 naming their contigs in a way that breaks TraCeR's parser. If you're using something like v2.0.4 then the workaround is to either upgrade to a later version (I've tested with Trinity v2.4.0) or to downgrade to Trinity v1.0.

Hope that helps. If not, please let me know and we can continue troubleshooting.

M

**Comment by yotamd** [comment]
Yes, that was the issue. Thank you!!

On Fri, May 19, 2017 at 11:40 AM, Mike Stubbington <notifications@github.com
