### ISSUE TITLE
CDR3

### ISSUE THREAD

**Issue by livnatje** [Teichlab/tracer#46]
Hi!

I'm using this code, and it's extremely useful! So, thanks a lot :)

One thing I'm not sure about is where I can find the *full* CDR3 sequence. Is the one you provide in the  recombinants.txt file the full CDR3 sequence or just a part of it? 

I used the .fa file in the filtered_TCR_seqs directory, but I'm still not sure where the CDR3 starts/ends. From comparisons to common CDR3 sequences it seems that it's broader than the sequence in the recombinants.txt file (the sequences between the V and J identifiers).

Would be great if you could clarify that.

Thanks!

**Comment by mstubb** [comment]
Hi Livnat,

Good to hear that TraCeR is proving useful!

At the moment, TraCeR doesn't report the full CDR3 sequences. However, it's clear that this would be useful for people so it's something that's on our development roadmap. 

I think that the best way to get CDR3 sequences currently will be to use the `.fa` file that's in `filtered_TCR_seqs` and to use something like the web version of IgBLAST (https://www.ncbi.nlm.nih.gov/igblast/igblast.cgi) to analyse them. IgBLAST will report the CDR3 sequence from pasted in nucleotide sequences. 

Do you want to extract CDR3s from a lot of reconstructed TCRs? If so, this approach will be tedious and time consuming! Let me know and we might be able to accelerate the CDR3 extraction code development and get you to beta test it. 

Best,

Mike

**Comment by livnatje** [comment]
Thanks for the quick response Mike!
I need to get the CDR3 of all the cells in the analysis. So far I parsed the .fa files, and just looked for an alignment with an external source of CDR3 sequences, assuming that the sub-sequence that gets aligned to a CDR3 sequence (from an external source) is probably a CDR3. Does that make sense? Do you have other suggestions?

**Comment by mstubb** [comment]
Yes, that sounds like it should work (assuming that the results you're getting look sane). Alternatively, you could concatenate all of your `.fa` files into one and then upload that to the IgBLAST website. It'll report the CDR3s for all of the sequences in the file. You could either copy and paste them from there or copy the entire output into a text file and parse that to extract the CDR3 sequences.

**Comment by livnatje** [comment]
That's what I'll do!
I tried igBLAST for a few sequences and I get Total identifiable CDR3 = 0, how would you interpret this?

**Comment by mstubb** [comment]
Hmmm. I'm not sure how IgBLAST deals with non-canonical CDR3s. If it can't identify them and all of the sequences you tried have sequences like this it may not be able to report them. 

Could you send me some examples of sequences that failed and I'll have a look and see if I can ascertain what's going on?

**Comment by livnatje** [comment]
Sure. Here are a few examples
[SS2CD45posP1_D01_TCRseqs.txt](https://github.com/Teichlab/tracer/files/1170390/SS2CD45posP1_D01_TCRseqs.txt)

**Comment by mstubb** [comment]
Thanks! I've just run them through the website and I get the attached output. It seems to be able to find CDR3s in each case. 

When you use the IgBLAST website, are you checking that you're analysing TCRs and not BCRs (there are tabs at the top of the page)? Also, make sure you select the correct species which seems to be human in this case. 

Hope that helps :)

[igblast_output.txt](https://github.com/Teichlab/tracer/files/1170400/igblast_output.txt)

**Comment by mstubb** [comment]
Hi Livnat,

Were you able to get this to work in the end? If so, I'll close the issue. 

Thanks!

Mike,

**Comment by livnatje** [comment]
Yes, I did. Thank you so much!

**Comment by lincoln-harris** [comment]
It would be very useful for us if Tracer automatically reported assembled CDR3s, perhaps in the cell_data.csv out file.  Is this something that can be implemented in future versions?

**Comment by mstubb** [comment]
It certainly could be although I can't guarantee when I'd have time to get it working. 

I'll gladly consider any pull requests that implement this. 

There's a pretty good start to this already in place as the `_get_cdr3_` method of the `Recombinant` class that's described in https://github.com/Teichlab/tracer/blob/master/tracerlib/core.py. CDR3s are already calculated in a fairly simple way for all the recombinants that are found and so it's mostly a case now of adding code that reports these.

**Comment by lincoln-harris** [comment]
But am I correct in saying that *most* of the CDR3 is already reported? Like for the A chain sequence `TRAV1-2_CTGTGCGGGGGAGGGGT_TRAJ13`, the middle segment is a mostly complete CDR3, right?

**Comment by mstubb** [comment]
Those are the ‘junctional nucleotides’ as reported by IgBLAST. They will be similar to the CDR3 but not the same.

**Comment by dcroote** [comment]
IgBLAST reports the CDR3 sequence when everything is correctly configured, but it appears that the [igblast command](https://github.com/Teichlab/tracer/blob/103888e3079b96aa059386699b65fed9a1f87081/tracerlib/tracer_func.py#L1238) is missing the `-auxiliary_data` argument and that the dockerfile is missing the associated `optional_file/` directory. Full [IgBLAST command examples here](https://ncbi.github.io/igblast/cook/examples.html) and more on the `optional_file` directory at the bottom of [this page](https://ncbi.github.io/igblast/cook/How-to-set-up.html)

**Comment by dcroote** [comment]
@mstubb I could put together a PR if you are interested?

**Comment by mstubb** [comment]
That’d be great, thanks. I’m struggling for time at the moment. 

M

**Comment by Rashedul** [comment]
> IgBLAST reports the CDR3 sequence when everything is correctly configured, but it appears that the [igblast command](https://github.com/Teichlab/tracer/blob/103888e3079b96aa059386699b65fed9a1f87081/tracerlib/tracer_func.py#L1238) is missing the `-auxiliary_data` argument and that the dockerfile is missing the associated `optional_file/` directory. Full [IgBLAST command examples here](https://ncbi.github.io/igblast/cook/examples.html) and more on the `optional_file` directory at the bottom of [this page](https://ncbi.github.io/igblast/cook/How-to-set-up.html)

That was very useful. Worked for me.
