### ISSUE TITLE
resources_dir is determined incorrectly

### ISSUE THREAD

**Issue by moskalenko** [Teichlab/tracer#51]
In tracer-0.5.1 the lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py imports base_dir, which results in the base_dir being set to the lib/python2.7/site-packages/tracer-0.5-py2.7.egg directory and, as a result, the resources directory is not found when tracer assemble is run. We had to patch the lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py script to take the base_dir location from an environment variable we set. However, that's just a workaround. A permanent fix still needs to be applied.

**Comment by mstubb** [comment]
This was fixed by pull request #52.

It is now possible to specify the location of the originally-downloaded resource files in the config file.
