### ISSUE TITLE
configparser missing from requirements.txt

### ISSUE THREAD

**Issue by krishnaroskin** [Teichlab/tracer#56]
The module configparser is required but missing from requirements.txt.

**Comment by mstubb** [comment]
`configparser` is part of the Python standard library so should be installed with Python. Are you having trouble using it with TraCeR?

**Comment by krishnaroskin** [comment]
Looks like it's called <configparser> in python3 but it's called <ConfigParser> in python2. So it's a good ol' 3 vs. 2 issue.

**Comment by mstubb** [comment]
Thanks! This should be fixed in the latest push to Master.
