### ISSUE TITLE
Difference in synthetic recombinome between tracer v0.4 and v0.5

### ISSUE THREAD

**Issue by orrzor** [Teichlab/tracer#61]
Hi TraCeR team!

I have a quick question that I think you could quickly answer. I have been using two version of TraCeR, the old v0.4 and more recent v0.5. I noticed large differences in the first step of aligning reads to the combinatorial recombinome. In particular, I had similar alignment rates of reads to the A chains between v0.4 and v0.5, but I had almost half the alignment rates of reads to the B chains in going from v0.4 to v0.5. In other words, fewer of my reads are aligning to the B chains (V,D,J) as I went from v0.4 to v0.5. I think I have tracked down this issue to the combinatorial recombinome. It seems like the file are the same across both version for the A chains, but the files are systematically smaller for the B chains as you go from v0.4 to v0.5. 
https://github.com/Teichlab/tracer/blob/v0.4.0/resources/synthetic_genomes/human/TCRB.fa
https://github.com/Teichlab/tracer/blob/master/resources/Hsap/combinatorial_recombinomes/TCR_B.fa
This is also true for the binary bt2 files.

Could you please tell me why you changed the recombinome files for the B chain during your update, and whether it's more accurate to use the more recent files? I would think it's better to have more of your reads aligning, but maybe there is something I am missing.

Thank you for your help! -Orr

**Comment by mstubb** [comment]
Hi Orr,

Thanks for the message. I changed the combinatorial recombine files between v0.4 and v0.5 because v0.5 introduces a `build` method that allows users to construct their own sequence resources beyond the human and mouse ones that are built in. For consistency, I re-built the mouse and human recombinomes using `build`. 

I've just had a look at the v0.4.0 and v0.5.0 TCRB files and they contain exactly the same V and J combinations. However, you're right that the files are smaller. This is because I included less of the constant (TRBC) region sequence in the newer versions so each sequence is shorter by exactly the same bases. 

I think that the reduction in alignments that you're seeing is due to not aligning reads that come from further into the constant region. These reads aren't informative for the recombined sequences and so I'd hope that this wouldn't make a difference to your TCR reconstruction success. Are you seeing a difference in the numbers of chains that you're able to reconstruct between the two versions? Please let me know if so.

Hope that makes sense and helps. Let me know if you want to discuss more.

Best,

Mike

**Comment by orrzor** [comment]
Hi Mike,

Thank you for getting back to me so quickly and explaining what the differences are!

I will try using the v0.4.0 TCRB files to see if that fixes the problem, but from what you are saying, it sounds like the problem may be after the initial read alignment to the V and J combinations. 

The other thing I will look into are the versions of Trinity and IgBLAST I am using, to see if that could be part of the problem. Do you think reducing the constant regions could affect Trinity's ability to build the contigs? I'm guessing you did not remove too much of the constant region, but could I be losing some reads that span the J and constant regions? 

Thanks for your help again. Best, Orr

**Comment by mstubb** [comment]
Hi Orr,

So this *is* preventing you from assembling chains in cells ie, you get TCR sequences for the same cells using v0.4.0 but _not_ v0.5.0?

How long are your reads? The v0.5.0 constant regions are 359 bases while those in v0.4.0 are 531. I'd expect that either should be sufficient. 

Not sure that the Trinity version would make much difference but do let me know if you find anything. 

Thanks for your input on this. It'd be good to know if we can improve reconstruction efficiency by going back to the longer constant regions. We didn't notice any differences in our testing but, of course, that doesn't mean that it's not the case in your situation. 

Best,

Mike

**Comment by orrzor** [comment]
Hi Mike,

Thank you. Yes, exactly. I am getting almost the same number of productive alpha chains between v0.5 and v0.4, but my number of productive beta chains drops by about 50%. It's very odd to me, as  reads aligning to the alpha and beta chain are processed the same way in your TraCeR program. So it's hard to come up with a change that would affect the beta chain but not the alpha, unless things have changed in the database of V and J segments (the recombinome), or Trinity is having a hard time with the B chain contigs, or my IgBLAST database is missing some B VDJ combinations (unlikely). Anyway these are the differences I am trying to track down. I will let you know what I am able to figure out. Thank you! Best -Orr

**Comment by mstubb** [comment]
That is odd. I'd be happy to look at a couple of examples of cells where you can reconstruct TCRB with v0.4.0 and it fails in v0.5.0 if that would help. Feel free to send the data over if you like.

**Comment by orrzor** [comment]
Hi Mike,

Thank you! I will send you some fastq files if I cannot track down the problem.

Best, Orr

**Comment by orrzor** [comment]
Hi Mike,

I am slowly tracking down the differences. I have switched to the old versions of the combinatorial recombinome, and now my fastq files are the same sizes for A and B chains when using v0.5 or v0.4. That's great.

Quick question, did the Trinity parameters that Tracer uses at all change between those versions (0.4 and 0.5)? I ask as I am using Trinity version 2, but was using Trinity 2.2 with v0.4 and Trinity 2.4 with v0.5. I know you say you use the defaults in the paper, but maybe those have changed in some way. Thanks! 

I think I'm very close to figuring out if the B chain loss is due to the sequences in the recombinome or the Trinity parameters. I found that all the segments I was losing in the B chain were coming from the J segment, ie I could get the V segment but not the J segment, potentially because of the shortening you did of the constant region at the 3' end. Not 100% sure yet though because of the potential differences in Trinity versions. I'll let you know what I find. Thanks so much for your help! -Orr

**Comment by mstubb** [comment]
Hi Orr,

We did alter the call to Trinity to stop it performing _in silico_ read normalisation by default in versions higher than 2.2 (in this commit https://github.com/Teichlab/tracer/commit/2cfe0e003ce6f25e4b5b6f0a74f4010ed56cb4e1). This was done *after* v0.5.0. 

Are you running the current master version from Github or a tagged release? If the latter, please can you try with the current master version instead? 

Also, I'm really intrigued by this and I'd be very grateful if you could send me the reads for just one of your cells where you're seeing differences between the versions so I can dig into it in parallel with you. Would that be ok? Feel free to send a link directly to my Sanger email if you don't want to share them through this issues page.

Thanks!

Mike

**Comment by orrzor** [comment]
Hi Mike,

Sorry for my slow reply! I tracked down the difference to the Trinity commands being issued, and then I found that the older version of TraCer had actually been modified by a former postdoc in the lab, and Brian H. They made changes to the kmer length and only running inchworm, when calling Trinity. I didn't realize the old version of TraCeR I was using had been modified in this way to run Trinity. Our reads are 38 nt, so these changes make some sense. The kmer length was decreased from 25 nt to 15 nt. 

Anyway, we get about twice as many beta chains reconstructed with this change. I am not sure still why it affects mostly the beta chains. I don't think these are false positives as the contigs have good E values when running IgBLAST. 

Thanks again for all your help! Best, Orr

**Comment by mstubb** [comment]
Hi Orr,

That makes sense and thanks for letting me know. I've been in touch with Brian and others from the Trinity team about folding their changes into the 'official' version of TraCeR so it's good to hear that they're helping with your sensitivity. 

I'll close this issue now but let me know if there's anything else I can do to help.

All the best,

Mike
