### ISSUE TITLE
naive question about tracer

### ISSUE THREAD

**Issue by GuidoLeoni** [Teichlab/tracer#69]
Thank you for your work with Tracer it is a very great tool
Might it be used also for analyzing rnaseq data from a mouse tumor tissue sample?
If yes according to your experience can be identified  a low confidence limit in the number of reads that contribute to identify a productive TCR? 
Best 
Guido

**Comment by mstubb** [comment]
Hi Guido,

Are you thinking of doing this on bulk or single-cell rnaseq from tumour tissue? 

Thanks,

Mike

**Comment by GuidoLeoni** [comment]
bulk rnaseq from tumor tissue (CT26 mice) sequenced with 60mln of PE reads

**Comment by mstubb** [comment]
Hi Guido,

I’m pretty confident that TraCeR would reconstruct *something* from this sort of data but we didn’t design it for this purpose and haven’t done any testing of its performance or accuracy when used on bulk data. It may well be better to try MiXCR for this:https://mixcr.readthedocs.io/en/master/

Hope that helps.

Very best,

Mike
