### ISSUE TITLE
Using Mouse C-region when organism is set to human

### ISSUE THREAD

**Issue by haseley** [Teichlab/tracer#7]
Hello,

   I was trying out your TRaCer algorithm (great work by the way).  I noticed when setting the organism to human in the configuration file, that the program was still attaching the mouse TCR alpha C region to the final sequence instead of the human C region.

**Comment by mstubb** [comment]
Hi @haseley thanks for spotting this! I've hopefully fixed it in the branch at https://github.com/Teichlab/tracer/tree/issue_7

Please can you test it with your data and let me know if it looks like it makes sense?

Thanks,

Mike

**Comment by haseley** [comment]
Thanks @mstubb 

I do have one question with regard to the code fix. I was trying to work through the logic for determining whether a rearrangement was in-frame and if changing the constant region would affect this.  I may have missed something in the code but, as far as I can tell, for both alpha and beta TCR chains, productivity and frame are determined by this call in line 744 of tracer_func.py:

productive_rearrangement = is_rearrangement_productive(best_V_seq + junction + best_J_seq + constant_seq[0:2])    

which checks to see if the length is evenly divisible by 3.  I tried pulling out the human alpha and beta TCR C genes from IMGT (http://www.imgt.org/genedb/fasta?outputFormat=fastaNAllP&selectGenes=TRAC&selectSpecies=Homo%20sapiens, http://www.imgt.org/genedb/fasta?outputFormat=fastaNAllP&selectGenes=TRBC1&selectSpecies=Homo%20sapiens, http://www.imgt.org/genedb/fasta?outputFormat=fastaNAllP&selectGenes=TRBC2&selectSpecies=Homo%20sapiens) and as far as I can tell TRAC is in the +2 reading frame, so adding two nucleotides from the constant sequence and checking if the length is divisible by three would be appropriate.  TRBC1 and TRBC2, however, seem to be in the +1 frame, so it seems like you would need to not add any sequence from the constant region before checking the length.

As a note I went back and also checked the mouse TCRA and TCRB (http://www.imgt.org/genedb/fasta?outputFormat=fastaNAllP&selectGenes=TRAC&selectSpecies=Mus%20musculus
http://www.imgt.org/genedb/fasta?outputFormat=fastaNAllP&selectGenes=TRBC1&selectSpecies=Mus%20musculus,   http://www.imgt.org/genedb/fasta?outputFormat=fastaNAllP&selectGenes=TRBC2&selectSpecies=Mus%20musculus) and it seems like the same issue exists with TCRA and TCRB not being in the same frame.  Did I miss where this is being handled or is this something that needs to be addressed?

Thanks!

**Comment by mstubb** [comment]
Hi @hasely,

I think this is to do with differences in sequence presentation between IMGT and Ensembl.

I took the TRBC sequences from ENSEMBL where they are displayed in the same frame as TRAC 

http://www.ensembl.org/Mus_musculus/Transcript/Sequence_cDNA?db=core;g=ENSMUSG00000076490;r=6:41538218-41539881;t=ENSMUST00000192856 <http://www.ensembl.org/Mus_musculus/Transcript/Sequence_cDNA?db=core;g=ENSMUSG00000076490;r=6:41538218-41539881;t=ENSMUST00000192856>

http://www.ensembl.org/Homo_sapiens/Transcript/Sequence_cDNA?db=core;g=ENSG00000211751;r=7:142720670-142793368;t=ENST00000633705 <http://www.ensembl.org/Homo_sapiens/Transcript/Sequence_cDNA?db=core;g=ENSG00000211751;r=7:142720670-142793368;t=ENST00000633705>

However, every functional J gene ends with the same nucleotide (G) and so I think IMGT show the TRBC sequence starting with a G even though that’s encoded by the J segment. Hope that makes sense.

Anyway, as far as I see it, the calculation of productivity works the way it’s done in TraCeR so it should be fine. You can check it yourself by translating the sequences from the `<cell_name>_TCRseqs.fa` in the `<cell_name>/filtered_TCR_seqs` folder that’s generated. Please let me know if you find any problems with this for human data, we have more experience with mouse.

Best wishes,

Mike

**Comment by haseley** [comment]
Hi @mstubb ,

   Thanks for the fix and your explanation.  

I'm hitting execution errors with the new branch.  I think all of the calls for get_fasta_line_for_contig_imgt/assembly were not updated to pass along the species (see for example line 531 of tracer_func.py).  I'm getting an error "get_fasta_line_for_contig_imgt() takes exactly 8 arguments (7 given)"

Also, I think the human TRAC sequence that you grabbed may include an untranslated exon (exon  4 is marked as untranslated in IMGT http://www.imgt.org/genedb/fasta?outputFormat=fastaNAllP&selectGenes=TRAC&selectSpecies=Homo%20sapiens and is not included in the ensembl output).  I'll let you know if I hit any additional issues.

Thanks again.

Nathan

**Comment by mstubb** [comment]
Thanks @haseley.

Apologies for the incomplete fix, I did it just before getting on a flight to Seattle! Anyway, the calls should now work and I’ve truncated the human TRAC sequence at the stop codon so that’s equivalent to all the other sequences. Please let me know if the code in that branch now works for you and, if it does, I’ll merge it into the main branch and close the issue.

Best wishes,

Mike

**Comment by haseley** [comment]
Works for me.  Have a great day!

Nathan

**Comment by mstubb** [comment]
Great. I've merged these changes into the main branch and I'll close the issue. Thanks for your help with this!

Mike
