### ISSUE TITLE
multiple TCR A/B for same cell? 

### ISSUE THREAD

**Issue by lincoln-harris** [Teichlab/tracer#72]
I'm seeing many cells for which Tracer reports multiple productive A or B chains. My understanding is that a given Tcell can only express a single A and a single B, so are the multiple A/B chains I'm seeing just computational artifacts?

**Comment by mstubb** [comment]
Hi Lincoln,

This paper gives a nice overview of the rates of allelic inclusion: http://www.jimmunol.org/content/185/7/3801 <http://www.jimmunol.org/content/185/7/3801>

Briefly, at the mRNA level you can expect ~30% of cells to express two productive alpha chains and 2–10% to express two productive betas. Many more can express one non-productive and one productive at either locus. 

If you are seeing rates that differ greatly from these or many cells with greater than two recombinants for either locus (in the unfiltered output from tracer) then you should give thought to whether these might be doublets or if there’s another explanation for what’s going on.

Hope that helps,

Mike
