### ISSUE TITLE
Failed running test with No successful Trinity assemblies

### ISSUE THREAD

**Issue by Rachael-rq** [Teichlab/tracer#76]
Hi Mike,

I ran into an error when running the ’tracer test',  the main message I could identify was 
```
...
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 --threads 1 -o 3 /hwfssz5/ST_CANCER/SCOL/USER/ruqian/tracer/test_data/results/cell1/Trinity_output/Trinity_cell1_TCR_B/chrysalis/inchworm.K25.L25.DS.fa.min100 /hwfssz5/ST_CANCER/SCOL/USER/ruqian/tracer/test_data/results/cell1/Trinity_output/Trinity_cell1_TCR_B/chrysalis/inchworm.K25.L25.DS.fa.min100
Error, cmd: /zfssz5/BC_PUB/Software/03.Soft_ALL/bowtie2-2.2.5/bowtie2-build --threads 1 -o 3 /hwfssz5/ST_CANCER/SCOL/USER/ruqian/tracer/test_data/results/cell1/Trinity_output/Trinity_cell1_TCR_B/chrysalis/inchworm.K25.L25.DS.fa.min100 /hwfssz5/ST_CANCER/SCOL/USER/ruqian/tracer/test_data/results/cell1/Trinity_output/Trinity_cell1_TCR_B/chrysalis/inchworm.K25.L25.DS.fa.min100 1>/dev/null 2>tmp.25342.stderr died with ret 256 at /zfssz5/BC_PUB/Software/03.Soft_ALL/Trinity-v2.6.5/PerlLib/Pipeliner.pm line 166
...
```
The full output has been attached 
[error.txt](https://github.com/Teichlab/tracer/files/2327588/error.txt

Would you say it'd be a problem of corrupted Bowtie 2 ?

Thanks a lot!

Lyu

**Comment by mstubb** [comment]
I’ve not seen this error before. 

Can you run bowtie2-build successfully outside TraCeR?

**Comment by Rachael-rq** [comment]
I had another look, I think it was calling bowtie2-build for options available in bowtie2 (--thread)

`bowtie2-build: unrecognized option '--threads'
...
/zfssz5/BC_PUB/Software/03.Soft_ALL/bowtie2-2.2.5/bowtie2-build --threads 2 -o 3 `

I have added the path of bowtie2 which contained executables for both bowtie2 and bowtie2-build to the $PATH , could that be causing confusion to tracer?


Thanks,
Lyu

**Comment by Rachael-rq** [comment]
Thanks Mike,

It's running successfully now. 
Yes, you were right, I didn't point to the executable in the tracer.conf file.

Cheers,
Lyu
