### ISSUE TITLE
Is there a docker file?

### ISSUE THREAD

**Issue by Krewn** [Teichlab/tracer#8]
The setup here isn't too crazy but it would be really nice if tracer was packaged in a docker container. See https://github.com/BioDocker/containers for examples : )

**Comment by mstubb** [comment]
Hi @Krewn. Yes, we agree that a Docker container would be really helpful for TraCeR :) It's definitely on our list of things to do!

Thanks,

Mike

**Comment by Krewn** [comment]
Yeah I think `RUN git clone ...` in a Docker-file can be squirrely when the head moves on a dependency...
