### ISSUE TITLE
problem understanding tracer output

### ISSUE THREAD

**Issue by hkoohy** [Teichlab/tracer#85]

**Comment by mstubb** [comment]
Hi Hashem, 

This issue is currently empty! Happy to help if you can add a bit more context :) 

Mike

**Comment by hkoohy** [comment]
Hi Mike,
Sorry to bother you again for another question:
In our tracer output (cell data file where we see clone groups and sizes), for some cells we both productive A and B chain, but the clonal_group and 'group_size' is left blanked! Does this mean  that the chains are unpaired?
please see the following for an example: 
many thanks
####
cell_name	A_productive	A_unproductive	B_productive	B_unproductive	clonal_group	group_size
P01-PP10A2-T3-S1-Sc_S98_L00_al	TRAV12-2_CCGTGGGTGGGA_TRAJ7				1	59
P01-PP10A4-T4-S2-Sc_S100_L00_a	TRAV12-2_GTGAAGGGAGGAAA_TRAJ47		TRBV4-1_GCCAATGGGGACAAGATA_TRBJ2-3		4	14
P01-PP10A5-T4-S2-Sc_S101_L00_a	TRAV12-2_TGAACGGAGACAAC_TRAJ21		TRBV2_AGCAGCCCCCCGGGGGAGCA_TRBJ2-7			
P01-PP10A6-T4-S2-Sc_S102_L00_a	TRAV12-2_GCCGTATCAGG_TRAJ45		TRBV4-1_CAGCCGTGCGGTCAGCGATAC_TRBJ2-3		13	5

**Comment by hkoohy** [comment]
It looks that these are singletons! right?

**Comment by mstubb** [comment]
Yes, exactly. If these entries are blank then that cell doesn't have any apparent clonal relationships and is a singleton.

**Comment by hkoohy** [comment]
thanks
