### ISSUE TITLE
Tracer clonotype network output

### ISSUE THREAD

**Issue by MungLAW** [Teichlab/tracer#91]
Hi there,

When I run the summarise process in TraCer, it's stuck in the process of dot drawing for very long time(more than 1 day) and I have to kill it in the end. I have check the detail of the drawing, and it seems like the dot cannot handle a large picture(about 900 cells). Could anyone give some tips about this issue?

And the dot files are here.
[dot.zip](https://github.com/Teichlab/tracer/files/3176579/dot.zip)

Many thanks

**Comment by mstubb** [comment]
Hi,

Yes, Dot is not good at laying out large networks (depending upon how many of your cells are connected). 

I'd suggest running `summarise` with the `--no_networks` option to stop it trying to draw the networks. It will then complete without needing to be killed and you can find alternative ways to interpret your data. 

It's worth noting that large network graphs with huge amounts of connectivity are very hard to interpret and so of relatively little value. 

Best,

Mike

**Comment by VicenteFR** [comment]
Hi,

Regarding this issue...
Just wondering if you can give a rough approximation of the maximum amount of cells dot can deal with in order to create the graph.

Many thanks

**Comment by mstubb** [comment]
We haven't systematically tested this. My sense is that it should be fine with hundreds of cells but will start to struggle beyond a few thousand. It'll depend a bit upon the amount of connectivity in your graph, the compute resources you have and your level of patience.
