### ISSUE TITLE
calling a deletion in IGK-J with igbalst 1.12.0

### ISSUE THREAD

**Issue by HLAmolec** [Teichlab/tracer#92]
Hello,

igblastn 1.12.0 is not calling a deletion in IGK-J with the following reference.  blastn has no problem calling it at the default settings.  I've tried to adjust the parameters to match blastn but the deletion was not called.  Igblast returns a blank for J-segment.  Do you have any suggestions how to make this work with igblast?

Thank you for your help.

here is the queried sequence:
```
>test_sequence
AGAGCCGCGGTCTTTCTCGATTGAGTGGCTTTGGTGGCCATGCCACCGCGCTCTTGGGGCAGCCGCCTTGCCGCTAGTGGCCGTGGCCACCCTGTGTCTGCCCGATTGATGCTGCCGTAGCCAGCTTTCCTGAGCCCTAGTGGCAGCCCAGGGCGACTCCTCATGAGTCTGCAGCTGCATTTTTGCCATATCCACTATTTGGAGTCTGACCTCCCTAGGAAGCCTCCCTGCTCCC
```
Here is the reference sequence:
```
>IGKDEL
GGTACCTGAAGAATTTTCAGGATCAACATTTGTAAGCATTATCAGCCCAGGATAATGCTTATTTACAGCAGTTCAACTTTTCTCACCTGCAGTAGTTTACTTTGATGAAATCCTGCTTATTTTTCACAATTAAAATTGCGTCCATGGCCCTTGTTACCCTTAAGAATTATATTTTGCTGACACAATCTCTTTATCTACATTTCACCTAAGTAAGCTTTTTCTTTACATGATTTTAAGTCATTTTCCAAAACAGAAAAGCATAATTATACAACCTTCTATGTGTATTGGAGGAAAAAAAGGGTCACACAAATAATAGTACACTCTCTCAGTTAAGGAGTAGGCAGGAGGAGGGGGTTGAGAAAGACAAACCAGAAAGAATTACATGAAATTTTCCTTCCTCCTCACTGAGCCTCCCTTGAATTGTCCAATAATATCCCCCCAACACACACACATAGACACAGAGCAGACTGTGAGGGACACGCAGCCTGGGTGGGACTCCAGGAGCCAGCTCTTACCCTAGAGTTTCTGCACGGGCAGCAGGTTGGCAGCGCACACTGTGGGAGCCCTAGTGGCAGCCCAGGGCGACTCCTCATGAGTCTGCAGCTGCATTTTTGCCATATCCACTATTTGGAGTCTGACCTCCCTAGGAAGCCTCCCTGCTCCCTAGGACAACCTGCTCTGACCTCTGAGGACCTGTCTGTAAACGTCCAGAGAAAAGCATGTGCCTGAAGGGTCTATGAAGGGGCTTGAGGCAAGTAGGGAGCCCAGCCCAGCTAACATTTGCAGCCATGGGATGGCTTTGTGTACCTAGAAAAGCAAAGATGAGGACTAGGCGAGCACAGGCCCCAAACGTTCACGATACACATCTCACTGCAAAGAAATGTCCTCTGGCCACTTTATAATGCAGCTCTAACTATAACTGGTGCTTTGCTGGTTTGTGGCCTGGGCTGGTCTCCCAGAGTCAGTGGCTTTGGGTGAGATGGCTCCAGGAGACAGCAGAAACTCTCATATATGAAGCCTTGCTTGCAGCGATTTGAGGCTTACTAGGGAAAAGCCATGATGGGTTTTATAGAGCATTAACTGTGATACGCCATCTAGGGCTGAGAGCTC

```

**Comment by mstubb** [comment]
Hi,

I'm a bit confused about what you're trying to do here. Please could you elaborate a bit? 

Is this a deletion that you're observing in some of your cells? Are you trying to use a custom reference? Is this mouse or human?

Thanks,

Mike

**Comment by HLAmolec** [comment]
Sorry for the confusion.  Correct, This is a deletion that is observed in some of the cells.
It is a custom made human reference, which works great with blastn, however, igblast doesn't call it.

Thanks

**Comment by mstubb** [comment]
Ah ok. Am I correct that the `test_sequence` you sent below is the J gene only? IgBLAST expects to first find a V gene; if it can't do that then it won't work properly? 

Do you have a rearranged IgK sequence containing a V gene upstream of the J with the deletion? 

Best,

Mike

**Comment by HLAmolec** [comment]
The V segment for that sequence is intronic rearrangement.  Also, a custom made reference that works well with igblast.
```
>IGKINTR
CGTGGCACCGCGAGCTGTAGACAGAGCCGCGGTCTTTCTCGATTGAGTGGCTTTGGTGGCCATGCCACCGCG
CTCTTGGGGCAGCCGCCTTGCCGCTAGTGGCCGTGGCCACCCTGTGTCTG
CCCGATTGATGCTGCCGTAGCCAGCTTTCCTG
```

**Comment by HLAmolec** [comment]
So, igblast returns IGKINTR for V but nothing for J.

**Comment by mstubb** [comment]
OK. So if you have sequences that contain IGKINTR–IGKDEL rearrangements and you're confident that your reference is correctly set up then I'm not sure why IgBLAST is failing. Maybe this is a question for the IGBLAST developers. 

Good luck!

Mike

**Comment by HLAmolec** [comment]
What is the best way to contact the IgBlast developers?
Thanks

**Comment by mstubb** [comment]
This page (https://ncbi.github.io/igblast/ <https://ncbi.github.io/igblast/>) suggests blast-help@ncbi.nlm.nih.gov
