### ISSUE TITLE
questions about input file and <cell_name> parameter

### ISSUE THREAD

**Issue by AlfredShawn** [Teichlab/tracer#93]
Hi Mike,

I have a question about how tracer handle or mark different cells in the pipeline. I installed and tested tracer without any problem. I get the "cell1" and "filtered_TCRAB_summary" folders under "results" successfully. 

I initially thought tracer will split the raw paired-end fastq files into single cell level fastqs based on cell bar codes and then perform the pipeline. However, when I tried to test with my own data, I put "cell" as the 'cell name' but only got one folder named cell. And I didn't find any information about cell index or barcodes in all output files. So does tracer require me to split the fastq files by myself and perform the pipeline at single cell level (run multiple times based on cell number)? I am confusing about it since there is no any documents mentioned about it in the tutorial. Look forward to your feedback. Thanks!

Attached is the shell script I created:
#!/bin/sh

TRACER=/scratch/TBI/Softwares/tracer2/tracer/tracer

#${TRACER}/tracer assemble -p 40 --loci A B  G D -c ${TRACER}/tracer.conf -s Hsap 2042-MN-1_S1_L001_R1_001.fastq.gz 2042-MN-1_S1_L001_R2_001.fastq.gz cell tracer_output

${TRACER}/tracer summarise -p 40 --loci A B  G D -c ${TRACER}/tracer.conf -s Hsap tracer_output

Yu

**Comment by mstubb** [comment]
Hi Yu,

Tracer requires demultiplexed fastq files such that each run is on a data from a single cell. 

Your mention of cell barcodes makes me think that you may be trying to run tracer on droplet-based scRNAseq data. Please note that this will not work. Tracer is intended for use with data from protocols that give sequencing reads from across the full length of each transcript (eg SmartSeq 2). 

Very best,

Mike
