### ISSUE TITLE
OSError: Required binary not found: bowtie2

### ISSUE THREAD

**Issue by gh22333** [Teichlab/tracer#94]
Hi, tracer test can't get pass the the bowtie2 not found error.    Bowtie2 is in the PATH and is in the tracer.conf file.   I tested with bowtie version 2.3.5 and version 2.3.4.3.   Thank you for looking into this.

bowtie2_path = /cm/shared/apps/bowtie/2.3.5
bowtie2-build_path = /cm/shared/apps/bowtie/2.3.5

Error:
Traceback (most recent call last):
  File "/cm/shared/apps/tracer/tracer", line 21, in <module>
    launch()
  File "/cm/shared/apps/tracer/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/cm/shared/apps/tracer/tracerlib/tasks.py", line 1224, in run
    loci=['A', 'B'], max_junc_len=50).run()
  File "/cm/shared/apps/tracer/tracerlib/tasks.py", line 370, in run
    self.align()
  File "/cm/shared/apps/tracer/tracerlib/tasks.py", line 421, in align
    bowtie2 = self.get_binary('bowtie2')
  File "/cm/shared/apps/tracer/tracerlib/tasks.py", line 69, in get_binary
    return check_binary(name, user_path)
  File "/cm/shared/apps/tracer/tracerlib/io.py", line 156, in check_binary
    .format(name=name))
OSError: Required binary not found: bowtie2. Please add to PATH or specify location in config file.

Annie

**Comment by mstubb** [comment]
The entry in your conf file needs to be the path to the binary, not the directory containing the binary. Can you try changing your file and see if it works? 

Alternatively, if bowtie2 is in your path you can just comment out those lines in the conf file and it should work. 

Let me know if that helps

Mike

**Comment by diazdc** [comment]
Hi, I know this issue is a bit dated, but I'm experiencing the same error and my path points directly to both binaries. Both bowtie2 and bowtie2-build are in my `PATH`. I've verified this using `which bowtie2` and `which bowtie2-build`. I've also tried commenting out both paths in the config file, but that didn't work either. Any help would be appreciated.

**Comment by mstubb** [comment]
Hi,

@diazdc please can you send me the output of `which bowtie2` and also your tracer config file?

Thanks!

Mike

**Comment by diazdc** [comment]
Hi @mstubb, thanks for getting back to me. This was an error on my part. The binary that wasn't found was for bowtie 1, which I didn't have installed.

**Comment by mstubb** [comment]
@diazdc - ok, great. Glad you got it worked out!
