### ISSUE TITLE
small test data

### ISSUE THREAD

**Issue by wangjiawen2013** [Teichlab/tracer#97]
Dear,
This is my first time to use TraCer. In the tutorial, it is said that TraCeR comes with a small dataset in test_data/ (containing only TCRA or TCRB reads for a single cell), while "There should be three cells, each with one productive alpha, one productive beta, one non-productive alpha and one non-productive beta. Cells 1 and 2 should be in a clonotype." So I am perplexed why three cells are generated with only a single cell.
Besides, the results showed that some non-TCR genes were expressed according to the Kallisto output, which was inconsistent with the description "containing only TCRA or TCRB reads for a single cell". I wanna know how to explain it.

**Comment by mstubb** [comment]
There is a test dataset containing sequencing reads from a single cell (`cell1`). This is used to test the `assemble` stage. 

The `test_data` directory also contains precomputed TraCeR output from two other cells (`cell2` and `cell3`). This is used in conjunction with the test assemblies to test the `summarise` stage. 

So, three cells in total. 

The precomputed data was generated from sequencing reads from the whole transcriptome of those cells and so the Kallisto outputs contain quantifications for other transcripts. I expect Kallisto is able to pseudo-align reads from the `cell1` data to some other transcripts and so will report quantifications for these. Given that this is a completely synthetic situation, you should ignore the Kallisto output for the test data.
